### ISSUE TITLE
Change Config classes to Value classes with builders.

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/appengine-plugins-core#723]
Replace and simplify Config Classes. Use `Path` instead of `File`
- [x] Infra to support it (#724) 
- [x] DeployConfiguration (#724)
- [x] DeployProjectConfigurationConfiguration, StageStandardConfiguration, StageFlexibleConfiguration (#727)
- [x] Update Deploy classes to use Path instead of File (#728)
- [x] Update Run/Stop Config (also use Path in those classes) (#729)
- [x] Update Versions Config (#731)
- [x] Remove "set" from setters on the builder (#732)
- [x] Update GenRepoInfo Config (#733) 
- [x] Remove last of `File` references from appengine.api package (#733)

DONE!

**Comment by elharo** [comment]
I prefer not doing this. It adds a dependency for code we can easily provide ourselves. In general I find magic generation frameworks to make code more opaque and harder to follow.

**Comment by loosebazooka** [comment]
The generated code is at compile time and is packaged with the Jar, but yeah, someone will have to look in `target/generated-sources/` to see them. These are value/builder classes with no logic, which is exactly where this framework is useful is removing excess boilerplate code.

**Comment by loosebazooka** [comment]
Update, we didn't use autobuilder. But all config's are now final value classes with builders. Lists might still be mutable. Might have to do something about that in the future.
